version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run: npm i
      - run: npm run compile

      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    docker:
      - image: circleci/node:10
      - image: trufflesuite/ganache-cli:v6.8.1-beta.0
        command: ganache-cli -k istanbul
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm run test
      - run: npm run lintNoFix
  coverage:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run: npm run coverage
  website:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run: cd website && npm i
      - run: cd website && npm run build
      - persist_to_workspace:
          root: '..'
          paths:
            - repo/website/dist
  publish:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # Push website
      - run: bash .circleci/deploy-ghpages.sh
workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
                - artifacts
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
      - coverage:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
      - website:
        requires:
          - build
        filters:
          branches:
            ignore:
              - gh-pages
              - artifacts
      - publish:
          requires:
            - website
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
