version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run: npm i
      - run: npm run compile

      - persist_to_workspace:
          root: '..'
          paths:
            - repo
            - .ssh
  test:
    docker:
      - image: circleci/node:10
      - image: trufflesuite/ganache-cli:v6.8.1
        command: ganache-cli -k istanbul
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: '..'

      - run: npm run test
      - run: npm run lintNoFix
      - run: npm run codechecks

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
                - artifacts
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
